### ISSUE TITLE
Error in init.sh

### ISSUE THREAD

**Issue by kmickeletto** [Fmstrat/samba-domain#12]
`case "$1" in
        start)
                if [[ -f /etc/samba/external/smb.conf ]]; then
                        cp /etc/samba/external/smb.conf /etc/samba/smb.conf
                        appStart
                else
                        echo "Config file is missing."
                fi
                ;;
`

cp should be set to cp -f so it will always overwrite what is in the local container.  Otherwise the admin will edit the smb.conf file outside of Docker (which they should be doing) and then restart the container and the change never gets activated.

**Comment by Fmstrat** [comment]
Fixed in https://github.com/Fmstrat/samba-domain/commit/2aefc30cc61747db7238d9392defb8e3040ded87
