### ISSUE TITLE
arm support

### ISSUE THREAD

**Issue by currowth** [Fmstrat/samba-domain#15]
Can you create a image for arm cpus? I was able to make the image work on the raspberry pi by only modifying the line to "FROM arm32v7/ubuntu:xenial" on the Dockerfile without making any change to your init script.

**Comment by Fmstrat** [comment]
I have added an `arm.Dockerfile` in `develop` (will get merged to `master`) that I will keep up to date, however there is no automated way in Docker HUB to build an ARM image that I can find. If you know of a way, please reopen and respond.
