### ISSUE TITLE
docker-compose

### ISSUE THREAD

**Issue by cgermanb** [Fmstrat/samba-domain#18]
query,
In the docker compose should not expose the ports?
When running the docker compose everything is generated correctly but the ports are apparently not available, possibly it is a mistake of mine but I am not understanding that it is missing.
Doing the build with docker worked perfectly on the first attempt.
regards
Charles

**Comment by burnbabyburn** [comment]
Ports are bound to the defined ip address. Did you modify it?

```192.168.3.222:53:53``` replace with ```<yourip>:53:53``` and so on.

**Comment by cfoellmann** [comment]
@cgermanb is this resolved otherwise this should be closed after soooo long
