### ISSUE TITLE
'{Access Denied} A process has requested access to an object but has not been granted those access rights.')

### ISSUE THREAD

**Issue by tardich** [Fmstrat/samba-domain#20]
Trying to run it through Kubernetes. Everything boots smoothly 'til "set_nt_acl_no_snum" where it fails with this error:

'{Access Denied} A process has requested access to an object but has not been granted those access rights.')

Any clue?

**Comment by DylanDonkersgoed** [comment]
I have the same error running via docker-compose.

**Comment by Fmstrat** [comment]
You need `--privileged` on the compose file.

**Comment by systemofapwne** [comment]
Why is privileged exactly necessary? I really do not want to grant this flag to any of my containers and would like to work around it (to only give access to what is actually needed rather than granting literally root)

**Comment by systemofapwne** [comment]
I did some research. Apparently, the priviliged flag is necessary, to work with UID > 65534 within a docker container. Otherwise, xattr will fail. Since I run all my containers via usernamespaces, priviliged will not work and thus causes the container to crash if ran withouth priviliged. According to https://github.com/lxc/lxc/issues/2708#issuecomment-473466062, you can force samba to restrict the UID range as you please, e.g. 655 - 65534. This will grant you at least 64879 unique UIDs which should be way more than you need on a small business.

**Comment by MohammedNoureldin** [comment]
@systemofapwne giving the container SYS_ADMIN privilege is enough to be able to use Samba in it. I have just tried it.

**Comment by systemofapwne** [comment]
> @systemofapwne giving the container SYS_ADMIN privilege is enough to be able to use Samba in it. I have just tried it.

Thanks. TBH, I gave up on this container and rather settled on a VM with Univention Corporate Server for managing my domain.
The reason: This container is not maintained anymore and crucial security fixes are not getting applied. Also a lot of headaches with this container.

**Comment by MohammedNoureldin** [comment]
@systemofapwne well if you have enough resources to have a dedicated VM for that then it is fine. I know it takes sometime to prepare it to be fully functional and secure, but asa you get it, you can celebrate (once and never touch it if not needed :D). For me I feel comfortable to configure containers and securing them using IPTables rules. As said, it is a bit tricky in the beginning, but then asa you get used to it, it is not that problematic anymore.

**Comment by burnbabyburn** [comment]
> @systemofapwne well if you have enough resources to have a dedicated VM for that then it is fine. I know it takes sometime to prepare it to be fully functional and secure, but asa you get it, you can celebrate (once and never touch it if not needed :D). For me I feel comfortable to configure containers and securing them using IPTables rules (of course that took me weeks to get to this point). As said, it is a bit tricky in the beginning, but then asa you get used to it, it is not that problematic anymore.

if you use this container u could have also gone the traefik/RProxy way. Works fine here
