### ISSUE TITLE
External smb.conf will not be copied to /etc/samba/smb.conf on restart

### ISSUE THREAD

**Issue by systemofapwne** [Fmstrat/samba-domain#24]
When changes are made on the external smb.conf (/etc/samba/external/smb.conf), the changes will not be copied over to /etc/samba/smb.conf, when you restart the container. In fact, this should be done or is expected (and probably was intended to work like this).

The culprit lies in init.sh: When the container starts, "init.sh setup" is called - Not only on the first build but on every startup. "setup" checks if /etc/supervisor/conf.d/supervisord.conf is present and if so, does nothing but starting the container regularily without copying over the external smb.conf (if present)

One way to fix it would be to copy the external smb file to /etc/samba in that situation too or rather use a symlink to the external smb.conf file instead.

**Comment by Fmstrat** [comment]
Ahh good catch. The whole `start` block should be part of `appStart`

**Comment by Fmstrat** [comment]
@systemofapwne Could you build/try the https://github.com/Fmstrat/samba-domain/tree/setup_fix branch?

**Comment by systemofapwne** [comment]
Yep, it works. It now copies over the cfg everytime I restart the container and also rebuilds the cfg, if it is missing. Thanks for the quick fix!

**Comment by Fmstrat** [comment]
Fixed with https://github.com/Fmstrat/samba-domain/commit/b41d78b205392f58fd9af63b95d4728b450de0f6
