### ISSUE TITLE
Any specific reason why "extnet" is present in the docker-compose examples but not in normal docker examples?

### ISSUE THREAD

**Issue by systemofapwne** [Fmstrat/samba-domain#25]
This is more a question than an issue.

The general docker examples do not add the container to a dedicated external network.
But the docker-compose examples feature an "extnet". I figured, that the container also works properly without that additional bridge. Is this just for the sake of "what can be done" or is it actually required? I rather think it's the first one.

**Feature**
I would rather drop that option entirely to reduce confusion or at least mark it as optional via a comment in the docker-compose file.

**Comment by suityou01** [comment]
Same :+1: 

ERROR: Network extnet declared as external, but could not be found. Please create the network manually using `docker network create extnet` and try again

What do I do now?

**Comment by suityou01** [comment]
Of course if you just do what the error tells you to do then it works :-D

docker network create extnet

Then I had to tweak the password complexity up a notch and it is running just fine :+1:

**Comment by systemofapwne** [comment]
Yes, it will just happily create the network. My question is whether this network is a necessity or not. For me, it looks arbitrary and out of place.

**Comment by suityou01** [comment]
I don't know enough to about LDAP to be able to help. I would say that even though I have the server running successfully in a Docker container I cannot connect to it. This is *with* the external network.

```ldapsearch -H ldap://192.168.1.102 -D cn=corp.example.come -w ThisIsMyAdminPassword! -b "o=localdc" objectclass=*
```

returns 

```ldap_sasl_bind(SIMPLE): Can't contact LDAP server (-1)```

Pretty uninformative.

**Comment by systemofapwne** [comment]
You should open another ticket then, since your problem seems to be not directly connected to the OP.
Anyways: I can successfully connect and authenticate my machine to the docker container. If you attempted to connect to the docker container from **another docker container**, you need to link the containers. If you do not want to do this, you can also use a shared "docker internal" network. For this methodem you now (and only now) need and "externel network" and having the samba-domain container a static IP assigned.

**Comment by Fmstrat** [comment]
Closed with commit https://github.com/Fmstrat/samba-domain/commit/76e3ca57bf9a1406c25e497ca13115a3b0267bcc
