### ISSUE TITLE
Adding secondary DC with JOIN does not add expected DNS entries

### ISSUE THREAD

**Issue by dafzor** [Fmstrat/samba-domain#29]
When running a second copy of the container to act as a secondary DC with JOIN the DNS entries are not properly created.

This means that the secondary DC does not properly replicate it's DNS entries to the main DC  and clients wont be to connect to the domain if the only the secondary DC is online.

**Comment by Fmstrat** [comment]
Closed due to age. @dafzor if you can reproduce and provide specifics on what you had to add manually, we can reopen.
