### ISSUE TITLE
Windows clients not registering in DNS

### ISSUE THREAD

**Issue by jasonsinclair5** [Fmstrat/samba-domain#30]
I have 2 systems, Windows 2019 server and Windows 10 that I was able to successfully join to the ad domain with no issues. Everything appears to be working properly, group policies, DNS resolution, etc. I can manage the DNS server via Windows DNS, but when I try a ipconfig /registerdns, I get a failure in the event log. I also noticed they weren't added when they were joined to the domain. They are static IP's, with just the samba DC as DNS, domain and register in DNS is checked. Is this supported? Just want to make sure before I spend hours trying to sift through logs, etc.

**Comment by corelgott** [comment]
We have exactly the same scenario and the same problem. Has anybody found a solutuion for this?

**Comment by jasonsinclair5** [comment]
> We have exactly the same scenario and the same problem. Has anybody found a solutuion for this?

The solution is to use dynamic DHCP with the ISC-DHCP server and a script. I was able to get this working, but I had to compile and install Samba separately and not use this docker build. I'm sure you could modify the docker image to install the DHCP server, but I went a separate route. The DNS registration with Windows clients isn't supported with Samba DNS. You have to disable that via Group Policy as it will fill up your logs with errors.

**Comment by Fmstrat** [comment]
Could this be related to NTP?

**Comment by jasonsinclair5** [comment]
> Could this be related to NTP?

I had NTP working and it was updating with no issues.

**Comment by Fmstrat** [comment]
NTP has been added at this point. If this is still an issue, please let us know.

**Comment by skuizy** [comment]
Seems fixed by https://github.com/Fmstrat/samba-domain/pull/48
