### ISSUE TITLE
Help: docker samba service client

### ISSUE THREAD

**Issue by chrisjd20** [Fmstrat/samba-domain#35]
Do you all have a docker of a samba service that would auth using this? 

I have a working version of this repo that creates a samba dc but im curious how I would have  a docker that could host just samba that hosts a share that would auth against my samba domain.

Feel free to close this if my question is too broad. I just figured I'd ask in case you all had a working example or link to one.

**Comment by Fmstrat** [comment]
I'm not sure this is possible, to be honest. You would end up needing to make a secondary DC as per the examples and add shares to it. I'm not aware of an external auth library that would accomplish this for samba. Please feel free to reopen if you are still investigating.
