### ISSUE TITLE
is this project still alive?

### ISSUE THREAD

**Issue by cfoellmann** [Fmstrat/samba-domain#36]
Hi guys,

i just started exploring setting up a new AD as 100% docker containers.
This container is the one with the most downloads on dockerhub.

When I launched a test container I just realized that the ENV for the NETBIOS name is `missing` so I look at this repo.
A lot of the issues are valid and should be fixed/merged if working correctly.

I know that maintaining an open project is time consuming and I only need to know if contributing (or trying to) will make a difference or if there is a fork that has merged some/most of these issues.

Appreciate any input from @Fmstrat or anyone else.

**Comment by burnbabyburn** [comment]
Let's see if he reports back Christian. With 4.16 released probably a lot of changes need to be fixed in my (not uploaded) version too. Finally we get cert auto enrollment!
Some fixes are under "closed pulls" and if this is rly abonded, i'll try to push a cleaned up version on my fork and push it back here.

**Comment by cfoellmann** [comment]
@burnbabyburn thanks for your reply.
I would be happy to help with "maintaining" a fork.

I just need to get into docker some more. Containers are pretty new to me but I am in the process of virtualizing everything in our environment. So anything that can go to docker does and the rest to a VM.

Can you point to a tutorial on starting containers directly from this (or fork) repo?

**Comment by Fmstrat** [comment]
@burnbabyburn interested in being a maintainer?

**Comment by burnbabyburn** [comment]
> @burnbabyburn interested in being a maintainer?

write access to devel branch would be beneficial.

**Comment by cfoellmann** [comment]
I think we should all test the @burnbabyburn version which is superb.
Then move the whole repo to that version!

**Comment by cfoellmann** [comment]
To all interested in a domain controller in docker I suggest using https://github.com/burnbabyburn/docker-ubuntu-samba-dc

**Comment by Fmstrat** [comment]
@burnbabyburn I will add you as a contributor. For some reason I did not get notifications on this topic.

**Comment by burnbabyburn** [comment]
> @burnbabyburn I will add you as a contributor. For some reason I did not get notifications on this topic.

I missed the time window for the invite :( Maybe you could issue an invite again.

**Comment by Fmstrat** [comment]
@burnbabyburn On it.

**Comment by Fmstrat** [comment]
Closed with new release
