### ISSUE TITLE
NOCOMPLEXITY not working

### ISSUE THREAD

**Issue by NickJH** [Fmstrat/samba-domain#4]
Hi,
I'm just trying this container and I am struggling with NOCOMPLEXITY. In the start up I've tried setting`-e "NOCOMPLEXITY=true" \` but each time the container exits. The logs show:

> Setting up sam.ldb users and groups
ERROR(ldb): uncaught exception - 0000052D: Constraint violation - check_password_restrictions: the password does not meet the complexity criteria!
  File "/usr/lib/python2.7/dist-packages/samba/netcmd/__init__.py", line 175, in _run
    return self.run(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/samba/netcmd/domain.py", line 442, in run
    nosync=ldap_backend_nosync, ldap_dryrun_mode=ldap_dryrun_mode)
  File "/usr/lib/python2.7/dist-packages/samba/provision/__init__.py", line 2172, in provision
    skip_sysvolacl=skip_sysvolacl)
  File "/usr/lib/python2.7/dist-packages/samba/provision/__init__.py", line 1795, in provision_fill
    next_rid=next_rid, dc_rid=dc_rid)
  File "/usr/lib/python2.7/dist-packages/samba/provision/__init__.py", line 1453, in fill_samdb
    "KRBTGTPASS_B64": b64encode(krbtgtpass.encode('utf-16-le'))
  File "/usr/lib/python2.7/dist-packages/samba/provision/common.py", line 55, in setup_add_ldif
    ldb.add_ldif(data, controls)
  File "/usr/lib/python2.7/dist-packages/samba/__init__.py", line 225, in add_ldif
    self.add(msg, controls)

I've had a look at your init.sh script and I'm wondering if the domain provisioning should happen after the complexity check but I'm too new to this to be able to check it out. Or have I set the flag incorrectly?

TIA,
Nick

**Comment by NickJH** [comment]
Just make a complex password rule then log into the container and change it with:
`samba-tool user setpassword administrator`

You can see the passwrd settings with:
`samba-tool domain passwordsettings show`

And change them with:

> samba-tool domain passwordsettings set --complexity=off
> samba-tool domain passwordsettings set --max-pwd-age=0
> samba-tool domain passwordsettings set --history-length=0
> samba-tool domain passwordsettings set --min-pwd-age=0
> samba-tool domain passwordsettings set --min-pwd-length=4
>

**Comment by NickJH** [comment]
Looks like I closed the issue by mistake in October. Reopening.

**Comment by Fmstrat** [comment]
@NickJH has the right idea. Set up the container with a complex password, revise the password, then set NOCOMPLEXITY as a workaround. As far as I know, there is no way to provision a domain without complexity using samba-tool. If someone knows of a way, let me know and I'll reopen.
