### ISSUE TITLE
cannot build 'develop' branch

### ISSUE THREAD

**Issue by cfoellmann** [Fmstrat/samba-domain#40]
in its current state I cannot build the `develop` branch.

Can we "go back" on the `develop` branch and use tested PRs to merge working changes?

I just tested going to ubuntu:focal which works great on master

**Comment by cfoellmann** [comment]
@Fmstrat can we restart the `develop` branch? or create a `1.0` branch?

**Comment by Fmstrat** [comment]
Closed with new release
