### ISSUE TITLE
Add ntp server support

### ISSUE THREAD

**Issue by hartimcwildfly** [Fmstrat/samba-domain#8]
Hi,
as windows clients try to get their time from the domain controller and the samba container got no ntp server running, clients won't receive the correct time. So I have to manually set it.
It would be very nice, if you could add a ntp server.

**Comment by zokradonh** [comment]
In my docker thinking I often prefer to separate services in different containers. NTP is a very independent service that should be solved with another image like `cturra/ntp` in my opinion.

But I think it should be mentioned in example `docker-compose.yml` and in `README.md`.

**Comment by Fmstrat** [comment]
Ref: https://wiki.samba.org/index.php/Time_Synchronisation

**Comment by Fmstrat** [comment]
@JinInRage This is completely untested, though should be straight forward. I've added `ntp` and an `/etc/ntpd.conf` based on the Samba recommendations. If you could give the new branch a try that would be great: https://github.com/Fmstrat/samba-domain/tree/ntpd

**Comment by Fmstrat** [comment]
@hartimcwildfly Were you able to test this?

**Comment by hartimcwildfly** [comment]
Sorry I did forget this and it could take some weeks until I test it.

**Comment by burnbabyburn** [comment]
> @hartimcwildfly Were you able to test this?

Pls have a look at pull #21

**Comment by Fmstrat** [comment]
Implemented in latest release.
